sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t shankar/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shankar/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    app: "dockerreact"
    region: "us-east-2"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-61764508338"
    bucket_path: "dockerreact"

    on:
        branch: master
    
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
